[project]
name = "project1"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "yfinance>=1.2.0",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.32.0",
    "hmmlearn>=0.3.3",
    "vectorbt>=0.28.2",
    "pyfolio>=0.9.2",
    "pandas-datareader>=0.10.0",
    "statsmodels>=0.14.6",
    "pandas>=2.3.3",
    "spicy>=0.16.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
    "setuptools<81",
]
